version: '2'
networks:
    public:
    upstream:
services:
    nginx:
        build: .
        ports:
            - "80:80"
            - "443:443"
        env_file: .env
        networks:
            - public
            - upstream
        volumes:
            # we need a couple of mounts since certbot uses symlinks for those files
            - ./cert/live:/etc/letsencrypt/live
            - ./cert/archive:/etc/letsencrypt/archive
